# Generated by Django 4.0.1 on 2022-12-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instituto',
            new_name='Institucion',
        ),
    ]
