# Generated by Django 4.0.1 on 2022-12-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0002_rename_instituto_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
