# Generated by Django 4.0.1 on 2022-12-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0005_alter_inscritos_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='institucion',
            field=models.ForeignKey(blank=True, default='Inacap', on_delete=django.db.models.deletion.CASCADE, to='seminario.institucion'),
        ),
    ]
