# Generated by Django 4.0.1 on 2022-12-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0006_alter_inscritos_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscritos',
            name='institucion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seminario.institucion'),
        ),
    ]
